### ISSUE TITLE
Safari color theme over saturated

### ISSUE THREAD

**Issue by GabrielF11** [GabrielF11/gabrielf11.ga#10]
The safari theme color is far too saturated.

Solution: Figure out how to get the RGBA converted to hex without it turning that ugly color. As it seems safari only read the RGB, and ignores the A (which must control the opacity).

![IMG_0091](https://user-images.githubusercontent.com/88408682/135352489-0bbd0995-821f-470d-8654-daeb6ce91ec5.png)

**Comment by Turtle84375** [comment]
This could help:
https://kilianvalkhof.com/2016/css-html/css-hexadecimal-colors-with-transparency-a-conversion-tool/

**Comment by GabrielF11** [comment]
Trying rn, thanks.

**Comment by GabrielF11** [comment]
So, it gave a more specific answer, but it’s still not the right shade. I think what happened is since it’s a gradient with white, it makes the color less saturated. So, later I’ll user a color picker on the website. Firefox has a built in one that’s pretty useful.

**Comment by GabrielF11** [comment]
Ok, so I used a color picker, but it turned out that safari doesn't support colors with transparency. wontfix.
