### ISSUE TITLE
Fix navbar dropdown UI issue

### ISSUE THREAD

**Issue by GabrielF11** [GabrielF11/gabrielf11.ga#11]
On the navbar, since it's made with bootstrap, I'm not sure how to change the distance between the navbar and the navbar dropdown. Because of this, on most browsers, the dropdown overlaps with navbar. Here's a picture:
![unknown](https://user-images.githubusercontent.com/88408682/135726898-3192a5c7-340b-4724-8556-0b7cb711c1cc.png)
Does anyone know how to fix this?

**Comment by Turtle84375** [comment]
Try adding `padding-top: ##px;` to the CSS for that element, 5 or 10px should be good enough, I think. (I could also try making a pull request if you want).

**Comment by GabrielF11** [comment]
Ok. I'll try that. Thanks for the help!

**Comment by GabrielF11** [comment]
Ok, so after some testing I found that `margin-top: 10px;` worked, but for some reason if I add that to the style.css or the <style> tag on the html it didn't work. For some reason, it ONLY works when I add the `style="margin-top: 10px;"` to the tag. Any ideas on why this is happening? Because If I did it that way, I would have to go through each dropdown on each page, which will take a while.

**Comment by Turtle84375** [comment]
Huh, weird, I'm not sure.

**Comment by GabrielF11** [comment]
I think I found the culprit...
![Screen Shot 2021-10-02 at 4 13 05 PM](https://user-images.githubusercontent.com/88408682/135734039-a406cd6b-0cbd-4883-b38e-4289baca29cf.png)
It's reading for that instead of my CSS. So I'll have to override that somhow in the style.css file I guess.

**Comment by GabrielF11** [comment]
Resolved with 
`.dropdown-menu[data-bs-popper] {
    margin-top: 10px;
}`
