### ISSUE TITLE
I'm Bored as separate respitory

### ISSUE THREAD

**Issue by GabrielF11** [GabrielF11/gabrielf11.ga#7]
I plan to re-do the i'm bored in markdown so anyone can contribute easily. This will also improve support for mobile devices, as the Bootstrap cards don't look great on it.

**Comment by Turtle84375** [comment]
So you're going to make it a different website? Because I don't think you can have the same domain on two different repositories...

**Comment by GabrielF11** [comment]
No, just so it's easier to contribute. It will probably still be at gabrielf11.ga/I'm-bored.

**Comment by GabrielF11** [comment]
> So you're going to make it a different website? Because I don't think you can have the same domain on two different repositories...

No, just so it's easier to contribute. It will probably still be at gabrielf11.ga/I'm-bored.

**Comment by Turtle84375** [comment]
Oh, ok.

**Comment by GabrielF11** [comment]
On second thought, I might just make the im bored into a MD file so it's very easy to edit. It seems too hard to make into a separate repository and have it at the domain.

**Comment by GabrielF11** [comment]
I actually don't even think it's possible (to have it on the same domain), so @Turtle84375 was right. Unless I got a different domain? hm.

**Comment by Turtle84375** [comment]
I mean, theoretically you could have it as a subdomain, but it'd take some research to put into place.

**Comment by GabrielF11** [comment]
Oh! Hmmm. I'll definitely look into that!

**Comment by GabrielF11** [comment]
Ok so far so good I got https://imbored.gabrielf11.ga/ up and running all that's left is to move it over! I kinda just guessed what to add since many websites weren't clear on how to do it. And it worked!

**Comment by Turtle84375** [comment]
Great!

**Comment by GabrielF11** [comment]
I'm actually staring to change my mind on this one. It might be too hard to get everything over, and I'd have to redo some stuff. Also, I found out that I can make the cards look really good with the glassmorphism, and that makes me not want to make it MD. If I don't end up moving it all the way over, I might just make it a redirect to it. Not sure what I'm gonna do yet though.

**Comment by GabrielF11** [comment]
The I'm bored page has been pretty much re-done! Now that it looks so good, I don't want to make it a MD file. I'm still not decided about moving the URL though.

**Comment by GabrielF11** [comment]
Update: I have begun the process of moving things over. I'm currently separating the site into to pages, websites and videos.

**Comment by GabrielF11** [comment]
The new website has been added! Now all that's left is to update the main site! That is planned for tomorrow.

**Comment by GabrielF11** [comment]
The updates are out! The development of the new I'm Bored page will be here: [github.com/gabrielf11/im-bored/issues](https://github.com/GabrielF11/Im-Bored/issues.)
